### ISSUE TITLE
Comments in python

### ISSUE THREAD

**Issue by Racker-Al** [PadreSJ/c101_Module2_Python#1]
On Episode 11 Dale stated that python 2.x does not include a way to create comment blocks. That is false so I wanted to drop you guys a note:

Python 2.7.5 (default, Aug 25 2013, 00:04:04) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

```
>>> # This is a comment line. I get dumped back into interpreter post comment
... 2 + 4
6
>>> """
... This is a comment block that adds newline characters 
... but continues to allow me to comment
... to exit I close out with 3 double quotes
... """
'\nThis is a comment block that adds newline characters\nbut continues to allow me to comment\nto exit I close out with 3 double quotes\n'
>>> Now I am back at the interpreter
  File "<stdin>", line 1
    Now I am back at the interpreter
        ^
SyntaxError: invalid syntax
>>>
```

**Comment by andrewguest** [comment]
Just to clarify, the triple quotes ''' are not _technically_ considered comments. They are considered docstrings, which basically perform the same function. The main difference is how docstrings are used in functions and can actually be prints by calling the "some_function.**docstring**" . Google can explain the differences between docstrings and comments better than I can.

Now having said that even Guido van Rossum says that it is fine to use docstrings as comments. I was just trying to explain the difference for anyone that is new to Python and tries to Google "python multi line comments" and sees someone say that Python doesn't have multi line comments.

**Comment by Racker-Al** [comment]
Fantastic explanation. I look forward to learning much more from you in the coming episodes. Closing the issue.

**Comment by tritium21** [comment]
... What?

Triple quotes are not comments, they are also not limited to docstrings.  They are simply string literals that accept literal newlines.  Thats all.  A docstring can be written with regular string literals.
